use super::naming;
use crate::error::{OrmError, Result};
use crate::ir::{OrmType, ScalarType};
use crate::shapes::{Shape, ShapeField};

const DART_RESERVED: &[&str] = &[
    "abstract", "as", "assert", "async", "await", "break", "case", "catch", "class", "const",
    "continue", "covariant", "default", "deferred", "do", "dynamic", "else", "enum", "export",
    "extends", "extension", "external", "factory", "false", "final", "finally", "for", "Function",
    "get", "hide", "if", "implements", "import", "in", "interface", "is", "late", "library",
    "mixin", "new", "null", "on", "operator", "part", "required", "rethrow", "return", "sealed",
    "set", "show", "static", "super", "switch", "sync", "this", "throw", "true", "try", "typedef",
    "var", "void", "when", "while", "with", "yield",
];

pub fn emit(shape: &Shape) -> Result<String> {
    shape.validate()?;
    naming::validate_identifiers(shape, DART_RESERVED, "Dart")?;
    let type_name = naming::type_name(shape);
    let mut out = String::from(
        "// GENERATED by ores-orm-core — derivative evidence, do not edit.\n\n\
         final class OresOptional<T> {\n\
           final bool isPresent;\n\
           final T? value;\n\
           const OresOptional.absent() : isPresent = false, value = null;\n\
           const OresOptional.present(T value) : isPresent = true, value = value;\n\
         }\n\n",
    );

    out.push_str(&format!("final class {type_name} {{\n"));
    for field in &shape.fields {
        let identifier = naming::identifier(&field.db_name, DART_RESERVED);
        out.push_str(&format!(
            "  final {} {identifier};\n",
            dart_field_type(field)?
        ));
    }

    out.push_str(&format!("\n  const {type_name}({{\n"));
    for field in &shape.fields {
        let identifier = naming::identifier(&field.db_name, DART_RESERVED);
        out.push_str(&format!("    required this.{identifier},\n"));
    }
    out.push_str("  });\n\n");

    out.push_str(&format!(
        "  factory {type_name}.fromJson(Map<String, Object?> json) {{\n"
    ));
    let allowed = shape
        .fields
        .iter()
        .map(|field| dart_string(&field.wire_name))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!("    const allowedKeys = <String>{{{allowed}}};\n"));
    out.push_str(
        "    final unknownKeys = json.keys.where((key) => !allowedKeys.contains(key)).toList();\n\
         if (unknownKeys.isNotEmpty) {\n\
           throw FormatException('unknown fields: $unknownKeys');\n\
         }\n",
    );
    if shape.kind.requires_non_empty_object() {
        out.push_str(
            "    if (json.isEmpty) {\n\
               throw const FormatException('patch must contain at least one field');\n\
             }\n",
        );
    }

    for field in &shape.fields {
        emit_dart_field_parse(&mut out, field)?;
    }

    out.push_str(&format!("\n    return {type_name}(\n"));
    for field in &shape.fields {
        let identifier = naming::identifier(&field.db_name, DART_RESERVED);
        out.push_str(&format!("      {identifier}: {identifier}Value,\n"));
    }
    out.push_str("    );\n  }\n}\n");

    return Ok(out);
}

fn emit_dart_field_parse(out: &mut String, field: &ShapeField) -> Result<()> {
    let identifier = naming::identifier(&field.db_name, DART_RESERVED);
    let key = dart_string(&field.wire_name);
    let raw = format!("{identifier}Raw");
    let check = dart_check(&field.ty, &raw)?;
    let nullable_check = if field.nullable {
        format!("{raw} == null || ({check})")
    } else {
        check
    };
    let converted = dart_convert(&field.ty, &raw)?;
    let converted = if field.nullable {
        format!("{raw} == null ? null : {converted}")
    } else {
        converted
    };

    if field.required {
        out.push_str(&format!(
            "    if (!json.containsKey({key})) {{\n\
                   throw const FormatException('missing required field: {}');\n\
                 }}\n\
                 final {raw} = json[{key}];\n\
                 if (!({nullable_check})) {{\n\
                   throw const FormatException('invalid field: {}');\n\
                 }}\n\
                 final {identifier}Value = {converted};\n",
            field.wire_name, field.wire_name
        ));
        return Ok(());
    }

    let field_type = dart_field_type(field)?;
    out.push_str(&format!(
        "    final {field_type} {identifier}Value = !json.containsKey({key})\n\
               ? const OresOptional.absent()\n\
               : (() {{\n\
                   final {raw} = json[{key}];\n\
                   if (!({nullable_check})) {{\n\
                     throw const FormatException('invalid field: {}');\n\
                   }}\n\
                   return OresOptional.present({converted});\n\
                 }})();\n",
        field.wire_name
    ));

    return Ok(());
}

fn dart_field_type(field: &ShapeField) -> Result<String> {
    let base = dart_type(&field.ty)?;
    let value = match (field.required, field.nullable) {
        (true, false) => base,
        (true, true) => format!("{base}?"),
        (false, false) => format!("OresOptional<{base}>"),
        (false, true) => format!("OresOptional<{base}?>"),
    };

    return Ok(value);
}

fn unsupported_scalar(name: &str) -> OrmError {
    OrmError::Unsupported(format!(
        "{name} requires an admitted cross-runtime wire/domain mapping before Dart emission"
    ))
}

fn dart_type(ty: &OrmType) -> Result<String> {
    let value = match ty {
        OrmType::Scalar(scalar) => match scalar {
            ScalarType::Boolean => "bool".to_owned(),
            ScalarType::Int16 | ScalarType::Int32 => "int".to_owned(),
            ScalarType::Int64 => return Err(unsupported_scalar("int64")),
            ScalarType::Float32 => return Err(unsupported_scalar("float32")),
            ScalarType::Float64 => "double".to_owned(),
            ScalarType::Decimal => return Err(unsupported_scalar("decimal")),
            ScalarType::String => "String".to_owned(),
            ScalarType::Uuid => return Err(unsupported_scalar("uuid")),
            ScalarType::Date => return Err(unsupported_scalar("date")),
            ScalarType::DateTime => return Err(unsupported_scalar("date-time")),
            ScalarType::Bytes => return Err(unsupported_scalar("bytes")),
            ScalarType::Json => "Object".to_owned(),
        },
        OrmType::Array(inner) => format!("List<{}>", dart_type(inner)?),
        OrmType::Named(name) => {
            return Err(OrmError::Unsupported(format!(
                "named ORM type {name} requires admitted contract mapping before Dart emission"
            )));
        }
    };

    return Ok(value);
}

fn dart_check(ty: &OrmType, value: &str) -> Result<String> {
    let check = match ty {
        OrmType::Scalar(scalar) => match scalar {
            ScalarType::Boolean => format!("{value} is bool"),
            ScalarType::Int16 => {
                format!("{value} is int && {value} >= -32768 && {value} <= 32767")
            }
            ScalarType::Int32 => format!(
                "{value} is int && {value} >= -2147483648 && {value} <= 2147483647"
            ),
            ScalarType::Int64 => return Err(unsupported_scalar("int64")),
            ScalarType::Float32 => return Err(unsupported_scalar("float32")),
            ScalarType::Float64 => format!("{value} is num && ({value} as num).isFinite"),
            ScalarType::Decimal => return Err(unsupported_scalar("decimal")),
            ScalarType::String => format!("{value} is String"),
            ScalarType::Uuid => return Err(unsupported_scalar("uuid")),
            ScalarType::Date => return Err(unsupported_scalar("date")),
            ScalarType::DateTime => return Err(unsupported_scalar("date-time")),
            ScalarType::Bytes => return Err(unsupported_scalar("bytes")),
            ScalarType::Json => format!("{value} != null"),
        },
        OrmType::Array(inner) => {
            let inner_check = dart_check(inner, "item")?;
            format!("{value} is List && {value}.every((item) => {inner_check})")
        }
        OrmType::Named(name) => {
            return Err(OrmError::Unsupported(format!(
                "named ORM type {name} requires admitted contract mapping before Dart emission"
            )));
        }
    };

    return Ok(check);
}

fn dart_convert(ty: &OrmType, value: &str) -> Result<String> {
    let converted = match ty {
        OrmType::Scalar(scalar) => match scalar {
            ScalarType::Boolean => format!("{value} as bool"),
            ScalarType::Int16 | ScalarType::Int32 => format!("{value} as int"),
            ScalarType::Int64 => return Err(unsupported_scalar("int64")),
            ScalarType::Float32 => return Err(unsupported_scalar("float32")),
            ScalarType::Float64 => format!("({value} as num).toDouble()"),
            ScalarType::Decimal => return Err(unsupported_scalar("decimal")),
            ScalarType::String => format!("{value} as String"),
            ScalarType::Uuid => return Err(unsupported_scalar("uuid")),
            ScalarType::Date => return Err(unsupported_scalar("date")),
            ScalarType::DateTime => return Err(unsupported_scalar("date-time")),
            ScalarType::Bytes => return Err(unsupported_scalar("bytes")),
            ScalarType::Json => value.to_owned(),
        },
        OrmType::Array(inner) => {
            let inner_type = dart_type(inner)?;
            let item = dart_convert(inner, "item")?;
            format!("({value} as List).map((item) => {item}).cast<{inner_type}>().toList()")
        }
        OrmType::Named(name) => {
            return Err(OrmError::Unsupported(format!(
                "named ORM type {name} requires admitted contract mapping before Dart emission"
            )));
        }
    };

    return Ok(converted);
}

fn dart_string(value: &str) -> String {
    return format!("'{}'", value.replace('\\', "\\\\").replace('\'', "\\'"));
}
