use super::naming;
use crate::error::{OrmError, Result};
use crate::ir::{OrmType, ScalarType};
use crate::shapes::{Shape, ShapeField};

const GLEAM_RESERVED: &[&str] = &[
    "as", "assert", "case", "const", "echo", "else", "fn", "if", "import", "let", "opaque",
    "panic", "pub", "todo", "type", "use",
];

pub fn emit(shape: &Shape) -> Result<String> {
    shape.validate()?;
    naming::validate_identifiers(shape, GLEAM_RESERVED, "Gleam")?;
    let type_name = naming::type_name(shape);
    let function_name = naming::identifier(
        &format!(
            "{}_{}",
            shape.table.replace('.', "_"),
            naming::shape_slug(shape.kind)
        ),
        GLEAM_RESERVED,
    );

    let mut out = String::from(
        "// GENERATED by ores-orm-core — derivative evidence, do not edit.\n\
         import gleam/dict\n\
         import gleam/dynamic\n\
         import gleam/dynamic/decode\n\
         import gleam/list\n\
         import gleam/option.{type Option}\n\n\
         pub type Presence(a) {\n\
           Missing\n\
           Present(a)\n\
         }\n\n\
         fn int16_decoder() -> decode.Decoder(Int) {\n\
           use value <- decode.then(decode.int)\n\
           case value >= -32_768 && value <= 32_767 {\n\
             True -> decode.success(value)\n\
             False -> decode.failure(0, expected: \"Int16\")\n\
           }\n\
         }\n\n\
         fn int32_decoder() -> decode.Decoder(Int) {\n\
           use value <- decode.then(decode.int)\n\
           case value >= -2_147_483_648 && value <= 2_147_483_647 {\n\
             True -> decode.success(value)\n\
             False -> decode.failure(0, expected: \"Int32\")\n\
           }\n\
         }\n\n",
    );

    out.push_str(&format!("pub type {type_name} {{\n  {type_name}(\n"));
    for field in &shape.fields {
        let identifier = naming::identifier(&field.db_name, GLEAM_RESERVED);
        out.push_str(&format!(
            "    {identifier}: {},\n",
            gleam_field_type(field)?
        ));
    }
    out.push_str("  )\n}\n\n");

    out.push_str(&format!(
        "fn {function_name}_decoder() -> decode.Decoder({type_name}) {{\n"
    ));
    for field in &shape.fields {
        let identifier = naming::identifier(&field.db_name, GLEAM_RESERVED);
        let key = gleam_string(&field.wire_name);
        let decoder = gleam_decoder(field)?;
        if field.required {
            out.push_str(&format!(
                "  use {identifier} <- decode.field({key}, {decoder})\n"
            ));
        } else {
            out.push_str(&format!(
                "  use {identifier} <- decode.optional_field({key}, Missing, {decoder} |> decode.map(Present))\n"
            ));
        }
    }
    out.push_str(&format!("  decode.success({type_name}(\n"));
    for field in &shape.fields {
        let identifier = naming::identifier(&field.db_name, GLEAM_RESERVED);
        out.push_str(&format!("    {identifier}:,\n"));
    }
    out.push_str("  ))\n}\n\n");

    let allowed = shape
        .fields
        .iter()
        .map(|field| gleam_string(&field.wire_name))
        .collect::<Vec<_>>()
        .join(", ");
    let valid_object = if shape.kind.requires_non_empty_object() {
        format!(
            "{{\n\
               case dict.size(fields) {{\n\
                 0 -> Error([decode.DecodeError(expected: \"non-empty patch object\", found: \"empty object\", path: [])])\n\
                 _ -> decode.run(data, {function_name}_decoder())\n\
               }}\n\
             }}"
        )
    } else {
        format!("decode.run(data, {function_name}_decoder())")
    };
    out.push_str(&format!(
        "pub fn decode_{function_name}(data: dynamic.Dynamic) -> Result({type_name}, List(decode.DecodeError)) {{\n\
           case decode.run(data, decode.dict(decode.string, decode.dynamic)) {{\n\
             Error(errors) -> Error(errors)\n\
             Ok(fields) -> {{\n\
               let allowed = [{allowed}]\n\
               let unknown = fields\n\
                 |> dict.keys\n\
                 |> list.filter(fn(key) {{ !list.contains(allowed, key) }})\n\
               case unknown {{\n\
                 [] -> {valid_object}\n\
                 [first, ..] -> Error([decode.DecodeError(expected: \"closed object\", found: first, path: [first])])\n\
               }}\n\
             }}\n\
           }}\n\
         }}\n"
    ));

    return Ok(out);
}

fn gleam_field_type(field: &ShapeField) -> Result<String> {
    let base = gleam_type(&field.ty)?;
    let value = match (field.required, field.nullable) {
        (true, false) => base,
        (true, true) => format!("Option({base})"),
        (false, false) => format!("Presence({base})"),
        (false, true) => format!("Presence(Option({base}))"),
    };

    return Ok(value);
}

fn unsupported_scalar(name: &str) -> OrmError {
    OrmError::Unsupported(format!(
        "{name} requires an admitted cross-runtime wire/domain mapping before Gleam emission"
    ))
}

fn gleam_type(ty: &OrmType) -> Result<String> {
    let value = match ty {
        OrmType::Scalar(scalar) => match scalar {
            ScalarType::Boolean => "Bool".to_owned(),
            ScalarType::Int16 | ScalarType::Int32 => "Int".to_owned(),
            ScalarType::Int64 => return Err(unsupported_scalar("int64")),
            ScalarType::Float32 => return Err(unsupported_scalar("float32")),
            ScalarType::Float64 => "Float".to_owned(),
            ScalarType::Decimal => return Err(unsupported_scalar("decimal")),
            ScalarType::String => "String".to_owned(),
            ScalarType::Uuid => return Err(unsupported_scalar("uuid")),
            ScalarType::Date => return Err(unsupported_scalar("date")),
            ScalarType::DateTime => return Err(unsupported_scalar("date-time")),
            ScalarType::Bytes => return Err(unsupported_scalar("bytes")),
            ScalarType::Json => "dynamic.Dynamic".to_owned(),
        },
        OrmType::Array(inner) => format!("List({})", gleam_type(inner)?),
        OrmType::Named(name) => {
            return Err(OrmError::Unsupported(format!(
                "named ORM type {name} requires admitted contract mapping before Gleam emission"
            )));
        }
    };

    return Ok(value);
}

fn gleam_decoder(field: &ShapeField) -> Result<String> {
    let base = gleam_decoder_type(&field.ty)?;
    if field.nullable {
        return Ok(format!("decode.optional({base})"));
    }

    return Ok(base);
}

fn gleam_decoder_type(ty: &OrmType) -> Result<String> {
    let value = match ty {
        OrmType::Scalar(scalar) => match scalar {
            ScalarType::Boolean => "decode.bool".to_owned(),
            ScalarType::Int16 => "int16_decoder()".to_owned(),
            ScalarType::Int32 => "int32_decoder()".to_owned(),
            ScalarType::Int64 => return Err(unsupported_scalar("int64")),
            ScalarType::Float32 => return Err(unsupported_scalar("float32")),
            ScalarType::Float64 => "decode.float".to_owned(),
            ScalarType::Decimal => return Err(unsupported_scalar("decimal")),
            ScalarType::String => "decode.string".to_owned(),
            ScalarType::Uuid => return Err(unsupported_scalar("uuid")),
            ScalarType::Date => return Err(unsupported_scalar("date")),
            ScalarType::DateTime => return Err(unsupported_scalar("date-time")),
            ScalarType::Bytes => return Err(unsupported_scalar("bytes")),
            ScalarType::Json => "decode.dynamic".to_owned(),
        },
        OrmType::Array(inner) => format!("decode.list({})", gleam_decoder_type(inner)?),
        OrmType::Named(name) => {
            return Err(OrmError::Unsupported(format!(
                "named ORM type {name} requires admitted contract mapping before Gleam emission"
            )));
        }
    };

    return Ok(value);
}

fn gleam_string(value: &str) -> String {
    return format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""));
}
