use super::naming;
use crate::error::{OrmError, Result};
use crate::ir::{OrmType, ScalarType};
use crate::shapes::{Shape, ShapeField};

const RUST_RESERVED: &[&str] = &[
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut",
    "pub", "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true", "try",
    "type", "unsafe", "use", "where", "while",
];

pub fn emit(shape: &Shape) -> Result<String> {
    shape.validate()?;
    naming::validate_identifiers(shape, RUST_RESERVED, "Rust")?;
    let type_name = naming::type_name(shape);
    let needs_required_nullable = shape
        .fields
        .iter()
        .any(|field| field.required && field.nullable);
    let needs_optional_non_null = shape
        .fields
        .iter()
        .any(|field| !field.required && !field.nullable);
    let needs_optional_nullable = shape
        .fields
        .iter()
        .any(|field| !field.required && field.nullable);

    // Do not derive schemars::JsonSchema here. Rust's Option<T> cannot by
    // itself represent all four required/optional × nullable/non-null states
    // without custom schema plumbing, and an inferred schema would therefore
    // be weaker than the canonical Draft 2020-12 artifact emitted alongside
    // this DTO. Serde is the executable Rust admission surface; JSON Schema is
    // emitted independently from the same Shape.
    let mut out = String::from(
        "// GENERATED by ores-orm-core — derivative evidence, do not edit.\n\
         // Canonical JSON Schema is emitted as a sibling artifact; do not infer it from this DTO.\n\
         #![allow(dead_code)]\n\n\
         #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]\n\
         #[serde(deny_unknown_fields)]\n",
    );
    out.push_str(&format!("pub struct {type_name} {{\n"));

    for field in &shape.fields {
        let identifier = naming::identifier(&field.db_name, RUST_RESERVED);
        let base = rust_type(&field.ty)?;
        let field_type = match (field.required, field.nullable) {
            (true, false) => base,
            (true, true) => format!("Option<{base}>"),
            (false, false) => format!("Option<{base}>"),
            (false, true) => format!("Option<Option<{base}>>"),
        };

        if identifier != field.wire_name {
            out.push_str(&format!("    #[serde(rename = {:?})]\n", field.wire_name));
        }
        match (field.required, field.nullable) {
            (true, true) => {
                out.push_str(
                    "    #[serde(deserialize_with = \"deserialize_required_nullable\")]\n",
                );
            }
            (false, false) => {
                out.push_str(
                    "    #[serde(default, deserialize_with = \"deserialize_optional_non_null\", skip_serializing_if = \"Option::is_none\")]\n",
                );
            }
            (false, true) => {
                out.push_str(
                    "    #[serde(default, deserialize_with = \"deserialize_optional_nullable\", skip_serializing_if = \"Option::is_none\")]\n",
                );
            }
            (true, false) => {}
        }
        out.push_str(&format!("    pub {identifier}: {field_type},\n"));
    }
    out.push_str("}\n");

    if shape.kind.requires_non_empty_object() {
        let absent = shape
            .fields
            .iter()
            .map(|field| {
                format!(
                    "self.{}.is_none()",
                    naming::identifier(&field.db_name, RUST_RESERVED)
                )
            })
            .collect::<Vec<_>>()
            .join(" && ");

        out.push_str(&format!("\nimpl {type_name} {{\n"));
        out.push_str("    pub fn validate(&self) -> Result<(), &'static str> {\n");
        if absent.is_empty() {
            out.push_str("        return Err(\"patch must contain at least one field\");\n");
        } else {
            out.push_str(&format!("        if {absent} {{\n"));
            out.push_str("            return Err(\"patch must contain at least one field\");\n");
            out.push_str("        }\n");
            out.push_str("        return Ok(());\n");
        }
        out.push_str("    }\n}\n");
    }

    if needs_required_nullable {
        out.push_str(
            "\nfn deserialize_required_nullable<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>\n\
             where\n\
                 D: serde::Deserializer<'de>,\n\
                 T: serde::Deserialize<'de>,\n\
             {\n\
                 return <Option<T> as serde::Deserialize>::deserialize(deserializer);\n\
             }\n",
        );
    }

    if needs_optional_non_null {
        out.push_str(
            "\nfn deserialize_optional_non_null<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>\n\
             where\n\
                 D: serde::Deserializer<'de>,\n\
                 T: serde::de::DeserializeOwned,\n\
             {\n\
                 let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;\n\
                 if value.is_null() {\n\
                     return Err(<D::Error as serde::de::Error>::custom(\"expected a non-null value\"));\n\
                 }\n\
                 let decoded = serde_json::from_value(value)\n\
                     .map_err(|error| <D::Error as serde::de::Error>::custom(error.to_string()))?;\n\
                 return Ok(Some(decoded));\n\
             }\n",
        );
    }

    if needs_optional_nullable {
        out.push_str(
            "\nfn deserialize_optional_nullable<'de, D, T>(deserializer: D) -> Result<Option<Option<T>>, D::Error>\n\
             where\n\
                 D: serde::Deserializer<'de>,\n\
                 T: serde::Deserialize<'de>,\n\
             {\n\
                 let value = <Option<T> as serde::Deserialize>::deserialize(deserializer)?;\n\
                 return Ok(Some(value));\n\
             }\n",
        );
    }

    return Ok(out);
}

fn rust_type(ty: &OrmType) -> Result<String> {
    let value = match ty {
        OrmType::Scalar(scalar) => match scalar {
            ScalarType::Boolean => "bool".to_owned(),
            ScalarType::Int16 => "i16".to_owned(),
            ScalarType::Int32 => "i32".to_owned(),
            ScalarType::Int64 => {
                return Err(OrmError::Unsupported(
                    "int64 requires an explicit Rust wire mapping".to_owned(),
                ));
            }
            ScalarType::Float32 => {
                return Err(OrmError::Unsupported(
                    "float32 requires an admitted cross-runtime wire/domain mapping before Rust emission".to_owned(),
                ));
            }
            ScalarType::Float64 => "f64".to_owned(),
            ScalarType::Decimal => {
                return Err(OrmError::Unsupported(
                    "decimal requires an explicit Rust wire mapping".to_owned(),
                ));
            }
            ScalarType::String => "String".to_owned(),
            ScalarType::Uuid => {
                return Err(OrmError::Unsupported(
                    "uuid requires an admitted canonical string/validator mapping before Rust emission".to_owned(),
                ));
            }
            ScalarType::Date => {
                return Err(OrmError::Unsupported(
                    "date requires an admitted semantic calendar-date mapping before Rust emission".to_owned(),
                ));
            }
            ScalarType::DateTime => {
                return Err(OrmError::Unsupported(
                    "date-time requires an explicit Rust wire mapping".to_owned(),
                ));
            }
            ScalarType::Bytes => {
                return Err(OrmError::Unsupported(
                    "bytes require an explicit Rust wire mapping".to_owned(),
                ));
            }
            ScalarType::Json => "serde_json::Value".to_owned(),
        },
        OrmType::Array(inner) => format!("Vec<{}>", rust_type(inner)?),
        OrmType::Named(name) => {
            return Err(OrmError::Unsupported(format!(
                "named ORM type {name} requires admitted contract mapping before Rust emission"
            )));
        }
    };

    return Ok(value);
}

#[allow(dead_code)]
fn _field_semantics(_: &ShapeField) {}
