use super::naming;
use crate::error::{OrmError, Result};
use crate::ir::{OrmType, ScalarType};
use crate::shapes::Shape;

pub fn emit(shape: &Shape) -> Result<String> {
    shape.validate()?;
    let type_name = naming::type_name(shape);
    let mut out = String::from(
        "// GENERATED by ores-orm-core — derivative evidence, do not edit.\n\
         import { z } from \"zod\";\n\n",
    );
    out.push_str(&format!("export const {type_name}Schema = z.object({{\n"));

    for field in &shape.fields {
        let key = serde_json::to_string(&field.wire_name).map_err(|error| {
            OrmError::Invalid(format!("could not encode TypeScript field name: {error}"))
        })?;
        let mut validator = zod_type(&field.ty)?;
        if field.nullable {
            validator.push_str(".nullable()");
        }
        if !field.required {
            validator.push_str(".optional()");
        }
        out.push_str(&format!("  {key}: {validator},\n"));
    }

    if shape.kind.requires_non_empty_object() {
        out.push_str(
            "}).strict().refine((value) => Object.keys(value).length > 0, { message: \"patch must contain at least one field\" });\n\n",
        );
    } else {
        out.push_str("}).strict();\n\n");
    }
    out.push_str(&format!(
        "export type {type_name} = z.infer<typeof {type_name}Schema>;\n"
    ));

    return Ok(out);
}

fn zod_type(ty: &OrmType) -> Result<String> {
    let value = match ty {
        OrmType::Scalar(scalar) => match scalar {
            ScalarType::Boolean => "z.boolean()".to_owned(),
            ScalarType::Int16 => "z.number().int().min(-32768).max(32767)".to_owned(),
            ScalarType::Int32 => "z.number().int().min(-2147483648).max(2147483647)".to_owned(),
            ScalarType::Int64 => {
                return Err(OrmError::Unsupported(
                    "int64 requires an explicit TypeScript wire mapping; JavaScript numbers cannot represent the full domain safely".to_owned(),
                ));
            }
            ScalarType::Float32 => {
                return Err(OrmError::Unsupported(
                    "float32 requires an admitted cross-runtime wire/domain mapping before TypeScript emission".to_owned(),
                ));
            }
            ScalarType::Float64 => "z.number().finite()".to_owned(),
            ScalarType::Decimal => {
                return Err(OrmError::Unsupported(
                    "decimal requires an explicit TypeScript wire mapping".to_owned(),
                ));
            }
            ScalarType::String => "z.string()".to_owned(),
            ScalarType::Uuid => {
                return Err(OrmError::Unsupported(
                    "uuid requires an admitted canonical string/validator mapping before TypeScript emission".to_owned(),
                ));
            }
            ScalarType::Date => {
                return Err(OrmError::Unsupported(
                    "date requires an admitted semantic calendar-date mapping before TypeScript emission".to_owned(),
                ));
            }
            ScalarType::DateTime => {
                return Err(OrmError::Unsupported(
                    "date-time requires an explicit TypeScript wire mapping".to_owned(),
                ));
            }
            ScalarType::Bytes => {
                return Err(OrmError::Unsupported(
                    "bytes require an explicit TypeScript wire mapping".to_owned(),
                ));
            }
            ScalarType::Json => "z.unknown()".to_owned(),
        },
        OrmType::Array(inner) => format!("z.array({})", zod_type(inner)?),
        OrmType::Named(name) => {
            return Err(OrmError::Unsupported(format!(
                "named ORM type {name} requires admitted contract mapping before TypeScript emission"
            )));
        }
    };

    return Ok(value);
}
